version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-feed
    versions:
    - 2.10.0
    - 2.12.0
  - dependency-name: gatsby-remark-copy-linked-files
    versions:
    - 2.7.0
    - 2.9.0
  - dependency-name: gatsby-remark-smartypants
    versions:
    - 2.7.0
    - 2.9.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.8.1
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: bl
    versions:
    - 1.2.3
