name: Trigger Netlify Build
on:
  schedule:
    # Run at 0815 daily
    - cron: '*/1 * * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: echo Hello, world!
