name: Trigger Cloudflare Pages Build
on:
  schedule:
    - cron: '15 8 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Request Cloudflare Pages Deploy Hook
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy hook
        shell: bash
        env:
          CLOUDFLARE_DEPLOY_HOOK: ${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}
        run: curl -X POST "$CLOUDFLARE_DEPLOY_HOOK"
